# -*- coding: utf-8 -*-
"""Fact Check 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH3WDnXu5DUUE1PpnHlTE1cnPc37GaC8
"""



"""# New Section"""

import pandas as pd
fake_news = pd.read_csv("/kaggle/Fake.csv")
true_news = pd.read_csv("/kaggle/True.csv")

# Add label columns
fake_news["label"] = 0
true_news["label"] = 1

df = pd.concat([fake_news, true_news], axis=0).sample(frac=1).reset_index(drop=True)
df = df[["text", "label"]]  #

# Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["label"], test_size=0.2, stratify=df["label"], random_state=42
)

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
import torch

model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

class NewsDataset(Dataset):
    def __init__(self, texts, labels):
        self.encodings = tokenizer(list(texts), truncation=True, padding=True, max_length=512, return_tensors="pt")
        self.labels = torch.tensor(labels.values if hasattr(labels, "values") else labels)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["labels"] = self.labels[idx]
        return item

train_dataset = NewsDataset(X_train, y_train)
test_dataset = NewsDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
model.to(device)

optimizer = AdamW(model.parameters(), lr=5e-5)

# Training loop (1 epoch for demo)
model.train()
from tqdm import tqdm

for batch in tqdm(train_loader):
    batch = {k: v.to(device) for k, v in batch.items()}
    outputs = model(**batch)
    loss = outputs.loss
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

from sklearn.metrics import accuracy_score, classification_report

model.eval()
preds, true_labels = [], []

with torch.no_grad():
    for batch in test_loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1)
        preds.extend(predictions.cpu().numpy())
        true_labels.extend(batch["labels"].cpu().numpy())

print("Accuracy:", accuracy_score(true_labels, preds))
print(classification_report(true_labels, preds))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(true_labels, preds)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'Real'])

plt.figure(figsize=(6, 5))
disp.plot(cmap=plt.cm.Blues, values_format='d')
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report, accuracy_score

print("Accuracy:", accuracy_score(true_labels, preds))
print(classification_report(true_labels, preds, target_names=["Fake", "Real"]))

# Assuming DL metrics are available like this
dl_accuracy = 0.92  # Example, update with your actual
dl_f1 = 0.91

# Best ML model
best_ml = results_df.sort_values(by='Test F1', ascending=False).iloc[0]

print("\n✅ A/B Testing Summary:\n")
print(f"Best ML Model: {best_ml['Model']}")
print(f"Accuracy: {best_ml['Test Accuracy']} vs. DL Accuracy: {dl_accuracy}")
print(f"F1 Score: {best_ml['Test F1']} vs. DL F1 Score: {dl_f1}")

if dl_f1 > best_ml['Test F1']:
    print("🎯 Deep Learning outperformed traditional ML in this case.")
else:
    print("✅ Traditional ML is performing competitively. Consider model complexity vs. performance.")

"""<h1>Machine Learning Models</h1>"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

# Combine both datasets
fake_news['label'] = 0  # Fake = 0
true_news['label'] = 1  # Real = 1

# Combine & shuffle
df = pd.concat([fake_news, true_news]).sample(frac=1, random_state=42).reset_index(drop=True)

# Features and labels
X = df['text']
y = df['label']

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_vect = vectorizer.fit_transform(X)

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_vect, y, test_size=0.2, stratify=y, random_state=42)

from sklearn.ensemble import GradientBoostingClassifier

# Add to model list
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "Decision Tree": DecisionTreeClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100)
}

# Train and evaluate
for name, clf in models.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(f"\n🧠 {name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred, target_names=['Fake', 'Real']))

from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Gradient Boosting": GradientBoostingClassifier()
}

# To store final evaluation
results = []

for name, model in models.items():
    # Cross-validation (5-fold)
    f1 = cross_val_score(model, X_train, y_train, cv=5, scoring='f1_macro').mean()
    acc = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy').mean()

    # Train on full train set
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Evaluate
    test_acc = accuracy_score(y_test, y_pred)
    test_f1 = f1_score(y_test, y_pred, average='macro')

    results.append({
        "Model": name,
        "CV Accuracy": round(acc, 4),
        "CV F1": round(f1, 4),
        "Test Accuracy": round(test_acc, 4),
        "Test F1": round(test_f1, 4)
    })

    print(f"\n📊 {name} Evaluation:\n")
    print(classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Convert results to DataFrame
results_df = pd.DataFrame(results)
print("\n🔍 Model Comparison Table:\n")
print(results_df)

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(data=results_df.melt(id_vars='Model'), x='Model', y='value', hue='variable')
plt.title("Model Comparison - Accuracy & F1 Scores")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# Assuming DL metrics are available like this
dl_accuracy = 0.9989  # Example, update with your actual
dl_f1 = 0.100

# Best ML model
best_ml = results_df.sort_values(by='Test F1', ascending=False).iloc[0]

print("\n✅ A/B Testing Summary:\n")
print(f"Best ML Model: {best_ml['Model']}")
print(f"Accuracy: {best_ml['Test Accuracy']} vs. DL Accuracy: {dl_accuracy}")
print(f"F1 Score: {best_ml['Test F1']} vs. DL F1 Score: {dl_f1}")

if dl_f1 > best_ml['Test F1']:
    print("🎯 Deep Learning outperformed traditional ML in this case.")
else:
    print("✅ Traditional ML is performing competitively. Consider model complexity vs. performance.")

